SUSE OpenStack Cloud Documentation
==================================

This is the source for the official SUSE OpenStack Cloud documentation.

Three books are currently available:

* Admin Guide
* Deployment Guide
* End User Guide

Released versions of these guides have been published at
https://www.suse.com/documentation/.


Branches
--------


.Overview of important branches
[options="header"]
|================================================
| Name                    | Purpose
| `maintenance/cloud_1.0` | Maintenance branch for 1.0
| `maintenance/cloud_2.0` | Maintenance branch for 2.0
| `maintenance/cloud_3.0` | Maintenance branch for 3.0
| `maintenance/cloud_4`   | Maintenance branch for 4
| `maintenance/cloud_5`   | Maintenance branch for 5
|================================================


Contributing
-------------

Admin and End User Guide::
	SUSE actively participates in the development of the Admin Guide and the End User Guide at openStack. The version available in this repository is a snapshot from the upstream repository. Therefore contributions should go to the upstream repositories. Refer to https://wiki.openstack.org/wiki/Documentation/HowTo for details.

Deployment Guide::
	If you would like to contribute to the Deployment Guide, please fork this repository and send pull requests. +
	Contributors with direct access to the repository are encouraged to use the git-flow-avh workflow (package `git-flow-avh`). However, this is not a must ;-).

.*No commits to master*
NOTE: Please do not make any commits to the `master` branch. `master` is reserved for releases only. 
