SUSE OpenStack Cloud Documentation
==================================

This is the source for the official SUSE OpenStack Cloud documentation.

Three books are currently available:

* Admin Guide
* Deployment Guide
* End User Guide

Released versions of these guides have been published at
https://www.suse.com/documentation/.


Branches
--------


.Overview of important branches
[options="header"]
|============================================================
| Name                             | Purpose
| `develop`                        | Current working branch
| `master`                         | Branch for most current released state
| `maintenance/cloud_1.0`          | Maintenance branch for SC 1.0
| `maintenance/cloud_2.0`          | Maintenance branch for SC 2.0
| `maintenance/cloud_3.0`          | Maintenance branch for SC 3.0
| `maintenance/cloud_4`            | Maintenance branch for SC 4
| `maintenance/cloud_5`            | Maintenance branch for SC 5
| `maintenance/openstack_cloud_6`  | Maintenance branch for SOC 6
| `maintenance/cloud_7`            | Maintenance branch for SOC 7
|============================================================


Contributing
-------------

Admin and End User Guide::
	SUSE actively participates in the development of the Admin Guide and the End User Guide at openStack. The version available in this repository is a snapshot from the upstream repository. Therefore contributions should go to the upstream repositories. Refer to https://wiki.openstack.org/wiki/Documentation/HowTo for details.

Deployment Guide::
	If you would like to contribute to the Deployment Guide, please fork this repository and send pull requests. +
	Contributors with direct access to the repository are encouraged to use the git-flow-avh workflow (package `git-flow-avh`). However, this is not a must ;-).

.*No commits to master*
NOTE: Please do not make any commits to the `master` branch. `master` is reserved for releases only. 

Building documentation
----------------------

If you're contributing to the cloud documentation in this repo and want to build using our DAPs tooling, see the DAPs Quickstart for more information: http://docserv.nue.suse.com/documents/DAPS/daps-quick/html/

If you are interested in building DAPs documentation (defaulting to HTML and PDF), you can utilise
our daps2docker project: https://github.com/openSUSE/daps2docker

1. Install Docker
2. Clone the daps2docker repository.
3. Run  `./daps2docker.sh /PATH/TO/DOC-DIR` or `/daps2docker.sh /PATH/TO/DC-FILE`.

