SUSE OpenStack Cloud Documentation
==================================

This is the source for the official SUSE OpenStack Cloud documentation.

Three books are currently available:

* Admin Guide
* Deployment Guide
* End User Guide

Released versions of these guides have been published at
https://www.suse.com/documentation/.


Branches
--------


.Overview of important branches
[options="header"]
|============================================================
| Name                             | Purpose
| `develop`                        | Current working branch
| `master`                         | Branch for most current released state
| `maintenance/cloud_1.0`          | Maintenance branch for SC 1.0
| `maintenance/cloud_2.0`          | Maintenance branch for SC 2.0
| `maintenance/cloud_3.0`          | Maintenance branch for SC 3.0
| `maintenance/cloud_4`            | Maintenance branch for SC 4
| `maintenance/cloud_5`            | Maintenance branch for SC 5
| `maintenance/openstack_cloud_6`  | Maintenance branch for SOC 6
| `maintenance/cloud_7`            | Maintenance branch for SOC 7
| `maintenance/cloud_8`            | Maintenance branch for SOC 8
|============================================================


Contributing
-------------

Thank you for contributing to this repo. Please adhere to the following guidelines when creating a pull request:

. Make your pull request against the _develop_ branch (not master) if you are contributing to the most recent release (currently
  Cloud 9). The _develop_ branch is protected and cannot be merged without review.

. If you are contributing to a previous release, please see _maintenance/cloud_<RELEASENUMBER>_. This branch is also 
  protected and cannot be merged without review.

. Make sure all validation (Travis CI) checks are passed, and tag relevant SMEs from the development team (if applicable)
  and members of the Cloud doc team: Carl Symons (csymons-suse), Dmitri Popov (dmpop) or Alexandra Settle (asettle).
  
  **NOTE:** If your pull request has multiple files and reorganisation changes, please build locally using DAPS or daps2docker
  (see instructions below) to verify and build the files. Travis CI only validates, and does not ensure the XML builds
  are correct.

. Implement any required changes, or fix any merge conflicts if relevant. If you have any questions, ping a documentation team
  member in #cloud-documentation on RocketChat.

. Once a review has been received from a documentation team member and any other SMEs, please merge your own PR.
  
  **NOTE:** If you need something merged ASAP, and a documentation team member is not available to re-review, but you have
  implemented any necessary changes, please use your best judgement and merge your own PR if STRICTLY NECESSARY. Alert
  a team member by pinging them in the #cloud-documentation channel.

Building documentation
----------------------

If you're contributing to the cloud documentation in this repo and want to build using our DAPS tooling, see the DAPS Quickstart for more information: https://opensuse.github.io/daps/doc/art.daps.quick.html

If you are interested in building DAPS documentation (defaulting to HTML and PDF), you can utilize
our daps2docker project: https://github.com/openSUSE/daps2docker

1. Install Docker
2. Clone the daps2docker repository.
3. Run  `./daps2docker.sh /PATH/TO/DOC-DIR` or `/daps2docker.sh /PATH/TO/DC-FILE`.
