#!/bin/bash
#script to search for all md files that contain both string X and Y


while [[ $1 = -* ]]; do
    arg=$1; shift  # shift the found arg away.

    case $arg in
         
        -h | --help)
echo "Usage: find2strings [string1] [string2]

This script helps you look for md files that contain two different strings.  The script is recursive.
 
-h, --help"
                        exit
            ;;
    esac
done
 

if [[ -z "$2" ]]
then
echo "This command requires two search strings."
exit 
fi

echo "Searching...this may take a while..."

for i in  `find . -name "*.md"`
do 

 if [[ `grep -l $1 $i` ]]
	then
	grep -H $2 $i  
fi

done
 echo " "
 echo "Finished searching"
 echo " "
 echo "If you got more results than you can read easily in the shell, use 
   find2strings [string1] [string2] > out.txt 
to send the results to a file named out.txt"
