// Copyright (C) 2014 Expitas LLC
// 
// WebWorksheet is the property of Expitas LLC and is protected by U.S. and international copyright law and conventions. 
// User acknowledges that access to WebWorksheet is limited to the License terms set forth herein and any expansion must be in writing. 
// The granting of the License to access and use WebWorksheet is conditioned on User's agreement not to disclose, copy, disseminate,
// redistribute, or publish any portion or excerpts of WebWorksheet or the data contained within to any other party.
// 
// Expitas does not make any warranties, express or implied, including, without limitation, those of merchantability and fitness for a particular 
// purpose, with respect to WebWorksheet. Although Expitas takes reasonable steps to screen for infection by viruses, worms, Trojan horses or other
// code manifesting contaminating or destructive properties before making WebWorksheet available, Expitas cannot guarantee that WebWorksheet will be
// free of infection.
// 
// In no event will Expitas be liable for: damages of any kind, including without limitation, direct, incidental or consequential damages 
// (including, but not limited to, damages for lost profits, business interruption and loss of programs or information) arising out of the use of or 
// inability to use WebWorksheet, or any claim attributable to errors, omissions or other inaccuracies in WebWorksheet or interpretations thereof.
// 
// User agrees to indemnify, defend and hold harmless Expitas, its affiliates, licensors, and their respective officers, directors, employees
// and agents from and against all losses, expenses, damages and costs, including reasonable attorneys' fees, arising out of the use of WebWorksheet
// by User or User's agent.

// webworksheetUpdate - used to release patches and new features between releases
// Version History
// 06/20/2013 - added HEX2DEC and DEC2HEX functions
// 08/29/2013 - updated calculate function to allow negative iterations
// 01/20/2014 - added wwsAdjustCell function
// 02/16/2014 - updated parseFormula to put parens around negative numbers to avoid x--y
// 02/16/2014 - updated submit function to add pre and post processing functions
// 02/16/2014 - added xml functions
// 02/25/2014 - updated wwsGoTo function to allow range of cells to be passed
// 02/25/2014 - updated wwsGetUrlData to fix error when no data was passed
// 02/28/2014 - updated getCellValue to return parameter if not a valid cell ID
// 03/06/2014 - added IRR function
// 03/24/2014 - corrected getInput to properly handle percentages < 1 with a leading zero
// 11/19/2014 - corrected applyFilterMenu to properly sort merged cells
// 12/10/2014 - added RATE function
// 02/19/2015 - corrected TEXT function to properly handle percentages
// 07/06/2015 - corrected formatFraction and Round to handle non-numbers
// 10/15/2015 - updated clearForm to force reload to avoid cache
// 11/17/2015 - corrected POWER function to eliminate rounding issue
// 02/09/2016 - added QUARTILE function

function HEX2DEC(a){if(!/^[0-9A-Fa-f]{1,10}$/.test(a))return xlErrNum;a=parseInt(a,16);return 549755813888<=a?a-1099511627776:a}
function DEC2HEX(a,b){if(isNaN(a))return xlErrValue;if(!/^-?[0-9]{1,12}$/.test(a)||-549755813888>a||549755813887<a)return xlErrNum;if(0>a)return(1099511627776+a).toString(16).toUpperCase();var c=parseInt(a,10).toString(16).toUpperCase();if("undefined"===typeof b)return c;if(isNaN(b))return xlErrValue;if(0>b)return xlErrNum;b=Math.floor(b);return b>=c.length?REPT("0",b-c.length)+c:xlErrNum};
function bcalculate(c){var d,b,a,f,g,e;if(!getInput(c))return document.getElementById("i"+c).value="",!1;if(manualCalculation&&"ALL"!=c&&"ONCE"!=c)return!0;0>iterations&&(c="ALL");try{e=getDependents(c).split(",")}catch(p){if("ALL"==c||"ONCE"==c){objectTags||(objectTags=document.getElementsByTagName("object"));d=[];for(e=0;e<objectTags.length;e++)"f"==objectTags[e].id.substring(0,1)&&d.push(objectTags[e].id.substr(1));e=d}else return applyConditionalFormats(c),!0}var m=!1;b="";statusMessageDisplay("Calculating...");
for(var k=0;k<Math.abs(iterations);k++){k==Math.abs(iterations)-1&&(m=!0);for(var l=0;l<e.length;l++)if(d=e[l],g=document.getElementById("f"+d)){b=g.getAttribute("formula");g=document.getElementById(d);var h=g.getAttribute("format"),n=getCategory(d,g);b=parseFormula(b);try{a=eval(b),void 0==a&&(a="")}catch(q){a="!ERROR"}switch(n){case "number":try{f=excel(a)}catch(r){f=a}"Infinity"==f&&(f=0);g.setAttribute("data-cval",f);b=0!=f||displayZeroes?formatNumber(f,h):" ";a=f;break;case "currency":b=formatCurrency(a,
h,d);break;case "date":b=formatDate(a,h);break;case "percentage":b=formatNumber(100*a,h)+"%";break;case "fraction":b=formatFraction(a,h);break;case "special":b=formatSpecial(a,h);break;default:isNumber(a)&&(a=parseFloat(a)),b=a.toString()}g.setAttribute("data-cval",a);m&&(g.innerHTML=b,applyConditionalFormats(d))}}applyConditionalFormats(c);statusMessageDisplay();return!0}
function wwsAdjustCell(b,a,c,d){var e=getCellValue(b);a||(a=1);a=e+a;null!=c&&null!=d&&(a<c||a>d)||(wwsSetCell(b,a),calculate("ALL"))}
function parseFormula(a){var e=[],g=0;if(null==a)return"";"#"==a.substring(0,1)&&(a=SQRT1_2(a.substr(1)));a=a.replace(/^=/,"");var d=a.match(/("[^"]*")/g);if(null!=d)for(var c=0;c<d.length;c++)a=a.replace(d[c],c+"str"),e[c]=d[c];a=a.replace(/\$/,"");d=a.match(/(\b[A-Z]{1,2}[0-9]+)/g);if(null!=d)for(c=0;c<d.length;c++){var f=document.getElementById(d[c]);if(null!=f){var b=getCellValue(d[c],f);switch(getCategory(d[c],f)){case "number":isNaN(parseFloat(b))&&(b=0);break;case "date":""==b&&(b=0);g++;break;
case "percentage":isNaN(parseFloat(b))&&(b=0);break;case "currency":isNaN(parseFloat(b))&&(b=0);break;case "general":if(!isNumber(b))try{b=b.replace(/\\/g,"\\\\"),b="'"+b.replace(/\'/g,"\\'")+"'"}catch(h){}}}else b=0;isNumber(b)&&0>b&&(b="("+b+")");a=a.replace(d[c],b)}-1<a.lastIndexOf("TODAY()")&&(a=a.replace(/TODAY\(\)/,TODAY()));-1<a.lastIndexOf("NOW()")&&(a=a.replace(/NOW\(\)/,NOW()));if(0<e.length&&(d=a.match(/(\d+str)/g),null!=d))for(c=0;c<d.length;c++)a=a.replace(d[c],e[c].replace(/\\/g,"\\\\"));
return a}
function submitForm(e){var g=document.getElementById("s"+e);e=g.getAttribute("label");onClickEvents(e);e=getElementsByTagNames("input,select,textarea");for(var h=0,k="",l=0,m="",d=0;d<e.length;d++){var c=e[d].id.substr(1);try{var n=document.getElementById(c).getAttribute("validation")}catch(r){n=""}if(n){var a=document.getElementById(n),p=parseInt(a.getAttribute("alertStyle")),b="";a.getAttribute("xlDVType")==xlValidateCustom?(b=eval(parseFormula(a.getAttribute("formula1"))),!1==b&&(b="")):b=document.getElementById(c).getAttribute("data-cval").toString().replace(/\ /g,
"");if(""==b){c="checkbox"==e[d].type?e[d].parentNode:e[d];switch(p){case xlValidAlertStop:h++;c.style.backgroundColor="Red";k=k+a.getAttribute("error")+crlf();break;case xlValidAlertWarning:l++,c.style.backgroundColor="Yellow",m=m+a.getAttribute("error")+crlf()}document.getElementById("iZZ99").onfocus="";document.getElementById("iZZ99").focus()}}}if(0<h)return alert(h+" required field(s) are missing and have been highlighted in red.\n\n"+k+"\nThose fields must be completed before the form can be submitted."),
!0;if(0<l&&!confirm(l+" recommended field(s) are missing and have been highlighted in yellow.\n\n"+m+"\nDo you wish to submit the form with missing fields?"))return!0;"function"===typeof beforeSubmitForm&&beforeSubmitForm();n=parseFormula(g.getAttribute("emailTo")).replace(/['&]/g,"");h=parseFormula(g.getAttribute("emailFrom")).replace(/['&]/g,"");k=parseFormula(g.getAttribute("emailSubject")).replace(/^'/,"").replace(/'$/,"");l=parseFormula(g.getAttribute("emailAttachment")).replace(/\'/g,"");m=
parseFormula(g.getAttribute("submitMessage")).replace(/^'/,"").replace(/'$/,"");g=parseFormula(g.getAttribute("nextPage")).replace(/^'/,"").replace(/'$/,"");b=getElementsByTagNames("tr");c=[];for(d=0;d<b.length;d++)if(a=b[d].id)"none"==getStyleById(a,"display").toLowerCase()?(a=document.getElementById(a),a.parentNode.removeChild(a)):c.push(a.substr(3));b=getElementsByTagNames("col");for(d=0;d<b.length;d++)if(0==parseInt("0"+b[d].width,10))for(a=getColumnLetter(d+1),p=0;p<c.length;p++){var q=a+c[p].toString();
try{var f=document.getElementById(q);f.parentNode.removeChild(f)}catch(s){}}f=getElementsByTagNames("td");for(d=0;d<f.length;d++)if(b=f[d].id)c=document.getElementById(b),b=document.getElementById(b).style,b.fontFamily=getStyle(c,"font-family"),b.fontSize=getStyle(c,"font-size"),b.textAlign=getStyle(c,"text-align"),a="",a=getStyle(c,"font-style"),"normal"!=a?b.fontStyle=a:"",a=getStyle(c,"font-variant"),"normal"!=a?b.fontVariant=a:"",a=getStyle(c,"font-weight"),"normal"!=a?b.fontWeight=a:"",a=getStyle(c,
"color"),"#000000"!=a?b.color=a:"",a=getStyle(c,"background-color"),"#000000"!=a?b.backgroundColor=a:"",a=getStyle(c,"border-top-width"),"0px"!=a?b.borderTop=a+" "+getStyle(c,"border-top-style")+" "+getStyle(c,"border-top-color"):"",a=getStyle(c,"border-left-width"),"0px"!=a?b.borderLeft=a+" "+getStyle(c,"border-left-style")+" "+getStyle(c,"border-left-color"):"",a=getStyle(c,"border-right-width"),"0px"!=a?b.borderRight=a+" "+getStyle(c,"border-right-style")+" "+getStyle(c,"border-right-color"):"",
a=getStyle(c,"border-bottom-width"),"0px"!=a?b.borderBottom=a+" "+getStyle(c,"border-bottom-style")+" "+getStyle(c,"border-bottom-color"):"";for(d=0;d<e.length;d++)if(c=e[d].id.substr(1),f=e[d].type,null!=document.getElementById(c))if("FILE"!=f.toUpperCase()){b=getCellValue(c);f=document.getElementById(c).getAttribute("category");a=document.getElementById(c).getAttribute("format");switch(f){case "currency":b=formatCurrency(b,a,c).toString();break;case "date":b=formatDate(b,a).toString();break;case "fraction":b=
formatFraction(b,a);break;case "number":b=formatNumber(b,a).toString();break;case "percentage":b=formatNumber(100*b,a)+"%";break;case "special":b=formatSpecial(b,a).toString();break;default:b=b.toString()}document.getElementById(c).innerHTML=null==b?"":b}else f=e[d].value,f=document.createTextNode(f.substr(f.lastIndexOf("\\")+1)),document.getElementById(c).appendChild(f);e=getElementsByTagNames("table");for(d=0;d<e.length;d++)f=e[d].id,0<f.indexOf("_calendar")&&(document.getElementById(f).outerHTML=
"");e=getElementsByTagNames("img");for(d=0;d<e.length;d++)e[d].src=e[d].src;document.getElementById("InputMessage").style.display="none";document.getElementById("CommentImage").style.display="none";e="<html>"+document.getElementsByTagName("html")[0].innerHTML+"</html>";e=e.replace(/<script[^<>]*>[\s\S]*?<\/script>/gi,"");e=e.replace(/<object [\S\s]*<\/object>/gi,"");e=e.replace(/<input[^<>]*>/gi,"");e=e.replace(/wwsInit\(\);/,'""');e=e.replace(/<col[^>]* width=[\"]?0px[\"]? [^>]*>/gi,"");with(document.forms[0])emailTo.value=
n,emailFrom.value=h,emailSubject.value=k,emailAttachment.value=l,submitMessage.value=m,nextPage.value=g,formHtml.value=e,action=wwsRelease+"/webworksheetEmailTest.asp",method="post";this.document.forms[0].submit();"function"===typeof afterSubmitForm&&afterSubmitForm();return!0}
function XMLToString(b){return window.ActiveXObject?b.xml:(new XMLSerializer).serializeToString(b)}
function createAjaxObject(){return window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP")}
function getXMLfile(b){var c=createAjaxObject();c.open("GET",b+"?"+Math.random(),!1);c.send();return c.responseXML}
function getXMLitem(b,c){for(var d=b.getElementsByTagName("ITEM"),a=0;a<d.length;a++){var e=d[a].getAttributeNode("name");if(e&&e.nodeValue.toLowerCase()==c.toLowerCase())return d[a].childNodes[0].nodeValue}return null}
function setXMLitem(b,c,d){for(var a=b.getElementsByTagName("ITEM"),e=0;e<a.length;e++){var f=a[e].getAttributeNode("name");if(f&&f.nodeValue.toLowerCase()==c.toLowerCase())return a[e].childNodes[0].nodeValue=d,b}}
function saveFile(b,c){var d,a=createAjaxObject();a.onreadystatechange=function(){4==a.readyState&&200==a.status&&(d=a.responseText)};a.open("POST","webworksheetSaveFile.php?"+Math.random(),!1);a.setRequestHeader("Content-type","application/x-www-form-urlencoded");a.send("filename="+b+"&filedata="+c);""!=d&&alert(d)}
function wwsGoTo(g,d){var h="";if(d){if(0>d.indexOf("|")){for(var b="",c=[],e=[],e=d.split(","),f=0;f<e.length;f++)if(isRange(e[f]))for(var c=getRangeValues(e[f]),a=0;a<c.length;a++)b+=c[a]+"|";else b+=getCellValue(e[f])+"|";d=b}a=g.replace(/(\w)*[\/]/g,"");b=rc4Encrypt(a,d);for(a=0;a<b.length;a++)c="0"+b.charCodeAt(a).toString(16),h+=c.substr(c.length-2);document.location=g+"?d="+h}else document.location=g}
function wwsGetUrlData(b){var a=document.location.href;if(0>a.lastIndexOf("="))return"";var c=a.substring(a.lastIndexOf("=")+1),a=a.replace(/\?d=\w*/,""),a=a.substring(a.lastIndexOf("/")+1);return rc4Decrypt(a,c).split("|")[b-1]}
function getCellValue(a){var b=document.getElementById(a);if(!b)return a;a=b.getAttribute("data-cval");null==a&&(a=b.value,void 0==a&&(a=b.childNodes[0],null!=a?"#text"==a.nodeName?(a=b.innerHTML.replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">"),a=a.replace(/\s*<a [^<>]*>/gi,"").replace(/<\/a>/gi,"")):a="A"==a.nodeName?a.innerHTML.replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">"):a.value:a=b.innerHTML));b=parseFloat(a);return b==a?b:a}
function IRR(){for(var c=[],a=0;a<IRR.arguments.length;a++)c[a]=IRR.arguments[a];for(var m=function(a,b,e){e+=1;for(var f=a[0],d=1;d<a.length;d++)f+=a[d]/Math.pow(e,(b[d]-b[0])/365);return f},n=function(a,b,e){e+=1;for(var f=0,d=1;d<a.length;d++)var c=(b[d]-b[0])/365,f=f-c*a[d]/Math.pow(e,c+1);return f},g=[],h=!1,b=!1,a=0;a<c.length;a++)g[a]=0===a?0:g[a-1]+365,0<c[a]&&(h=!0),0>c[a]&&(b=!0);if(!h||!b)return xlErrNum;var a=0.1,l,k,h=0,b=!0;do k=m(c,g,a),b=a-k/n(c,g,a),l=Math.abs(b-a),a=b,b=1E-10<l&&
1E-10<Math.abs(k);while(b&&50>++h);return b?xlErrNum:a}
function getInput(c){var b="i"+c;if(null!=document.getElementById(b)){var d=document.getElementById(c).getAttribute("category"),e=document.getElementById(c).getAttribute("format"),g=document.getElementById(c).getAttribute("validation"),f=document.getElementById(b).type.toUpperCase(),a=document.getElementById(b).value,a=a.replace(/(^ +)|( +$)/g,""),a=a.replace(/<script|<a/g,"");switch(d){case "number":a=a.replace(/[\$\,\%\ ]/g,"");"select"!=document.getElementById(b).tagName.toLowerCase()&&""!=a&&
(document.getElementById(b).value=formatNumber(a,e));""==a&&(a=0);document.getElementById(c).setAttribute("data-cval",a);break;case "percentage":f=/\%/.test(a);a=a.replace(/\%/g,"");"select"!=document.getElementById(b).tagName.toLowerCase()&&(1>a&&-1<a&&"0"!=a.substr(0,1)&&!f&&(a*=100),document.getElementById(b).value=formatNumber(a,e)+"%",a/=100);document.getElementById(c).setAttribute("data-cval",a);break;case "fraction":a=a.replace(/ /,"+");b=/^-/;e=!1;b.test(a)&&(e=!0,a=a.replace(b,""));try{a=
eval(a),void 0==a&&(a="")}catch(h){}e&&(a="-"+a);document.getElementById(c).setAttribute("data-cval",a);break;case "currency":a=a.replace(/[\$\,]/g,"");"select"!=document.getElementById(b).tagName.toLowerCase()&&(document.getElementById(b).value=formatCurrency(a,e,b));document.getElementById(c).setAttribute("data-cval",a);break;case "date":d=isDate(a);if(null==d)if(d=isTime(a),null==d){document.getElementById(b).value=a;document.getElementById(c).setAttribute("data-cval",a);break}else a=new Date(d),
d=unixToExcelDate(d-gmtOffset)+a.getHours()/24+a.getMinutes()/1440+(a.getSeconds()+1)/86400;document.getElementById(c).setAttribute("data-cval",d);"SELECT-ONE"!=f&&(document.getElementById(b).value=formatDate(d,e));a=d;break;default:document.getElementById(b).value=a,document.getElementById(c).setAttribute("data-cval",a)}if(null!=g&&""!=a&&!validate(document.getElementById(g),a))return!1}return!0};
function applyFilterMenu(b,c,f,k){for(var d=COLUMN(b),g=0,a=1;a<=COLUMN(b);a++)document.getElementById(getColumnLetter(a)+(c-1).toString())&&g++;document.getElementById("FilterMenu").style.display="none";for(var a=document.getElementById("fmSelect"),e=0;e<a.options.length;e++)if(1==a.options[e].selected){var h=a.options[e].value;break}switch(h){case "sortasc":sortUserData(g,c,f,k,"asc");break;case "sortdesc":sortUserData(g,c,f,k,"desc");break;case "":break;default:"(All)"==h?(hasFilter[d]=!1,filterValues[d]=
"",document.getElementById("a"+b).src="http://www.webworksheet.com/filterOFF.jpg"):(hasFilter[d]=!0,filterValues[d]=h.toLowerCase(),document.getElementById("a"+b).src="http://www.webworksheet.com/filterON.jpg"),filterUserData(c,f)}}
function RATE(f,g,h,d,e,b){b=void 0===b?.01:b;d=void 0===d?0:d;e=void 0===e?0:e;f=parseFloat(f);g=parseFloat(g);h=parseFloat(h);d=parseFloat(d);e=parseFloat(e);b=parseFloat(b);var c,k,m,l=0,n=c=0,a=b;1E-10>Math.abs(a)||(c=Math.exp(f*Math.log(1+a)));b=h+g*f+d;k=h*c+g*(1/a+e)*(c-1)+d;n=m=0;for(l=a;1E-10<Math.abs(b-k)&&50>n;)a=(k*m-b*l)/(k-b),m=l,l=a,1E-10>Math.abs(a)?c=h*(1+f*a)+g*(1+a*e)*f+d:(c=Math.exp(f*Math.log(1+a)),c=h*c+g*(1/a+e)*(c-1)+d),b=k,k=c,++n;return a}
function TEXT(c,b){var a=/%/;if(a.test(b))return formatNumber(100*c,b)+"%";a=/[0#]/;if(a.test(b))return formatNumber(c,b);a=isDate(c);return null!=a?formatDate(a,b):c}
function formatFraction(a,f){var d=1,b=1,c=1,g=1,e="";if(!isNumber(a)||0==a)return 0;if(parseFloat(a)==parseInt(a)&&!isNaN(a))return a;0>a&&(e="- ",a=Math.abs(a));if(0==a%.03125){d=Math.floor(a);b=(a-d)/.03125;for(c=32;ISEVEN(b);)b/=2,c/=2;0<d&&(b=d+" "+b);return e+b+"/"+c}for(;ROUND(d,2)!=ROUND(a,2)&&(d<a?b+=1:(c+=1,b=parseInt(a*c)),d=b/c,1E3!=++g););if(b<c)return b+"/"+c;d=Math.floor(b/c);b=formatFraction(a-d,f);return e+d+" "+b}
function ROUND(a,b){if(!isNumber(a))return 0;if(0<=b)return a.toFixed(b);var c=Math.pow(10,Math.abs(b));return(Math.floor(a)/c).toFixed(0)*c}
function clearForm(a){window.location.reload(!0);return!0}
function POWER(a,b){return parseFloat(Math.pow(a,b))}
function QUARTILE(c,a,d){a*=.25;var b=6==d?a:1-a;c=getRangeValues(c);ascending=function(a,b){return a-b};c.sort(ascending);d=c.length;a=d*a+b;b=MAX(MIN(INT(a),d),1);return 0<=a-b&&b<d?(1-(a-b))*c[b-1]+(a-b)*c[b]:c[b-1]}
function saveForm(a,b,c,d){onClickEvents(a);unHilite();if("local"==b||""==b)a="To save this file on your local machine, click OK and wait for the page to refresh.",a="MSIE"==browser?a+"\n\nThen, using the File..Save As menu option, save the file selecting the Type as Webpage, HTML only.":a+"\n\nThen, right click and select the Save as... option, selecting the Type as Web Page, Complete.",alert(a);else if("1"!=c){var e=window.prompt("A password is required to save any changes:","");if(!e)return alert("No password entered. Changes will not be saved."),
!1;var g=1;for(a=1;a<=e.length;a++)g=Math.sqrt(e.charCodeAt(a-1)*g*a);a=g.toString().replace(/\./,"").substring(0,10);if(c!=a)return alert("Incorrect Password.  Changes will not be saved."),!1}c=getElementsByTagNames("input,select,textarea");for(a=0;a<c.length;a++)if(e=c[a].id,g=e.substr(1),null!=document.getElementById(g)){var f=getCellValue(g);document.getElementById(e).setAttribute("data-default",f);document.getElementById(g).innerHtml=f}a="<html>"+document.getElementsByTagName("html")[0].innerHTML+
"</html>";with(document.forms[0]){formHtml.value=escape(a);formHtml.value=formHtml.value.replace(/\+/g,"%2B");if("shared"==b){b=document.location.href;if(null==d)sharedFile.value=b;else{/^[A-Z]{1,2}[0-9]+$/.test(d)&&calculate(d);sharedFile.value=parseFormula(d).replace(/['&]/g,"")}action=b.substring(0,b.lastIndexOf("/"))+"/webworksheetShared.php"}else action=wwsRelease+"/webworksheetSave.asp";method="post";submit()}return!0}